balloon/config/routes.rb
Rails.application.routes.draw do
  # get 'goals/new'
  # get 'goals/index'
  # get 'goals/create'
  # get 'goals/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # get 'users/new'
  # get 'users/create'
  # get 'users/show'

  resources :users, only: [:new, :create, :show] do
    resources :goals, only: [:new, :index, :create, :destroy, :edit]
  end
  resources :goals, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

balloon/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

balloon/app/models/goal.rb
class Goal < ApplicationRecord

  belongs_to :user

end

balloon/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

  after_initialize :ensure_session_token
  attr_reader :password
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  has_many :goals

end

balloon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
   
  def login(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user 
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
    @current_user = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    render users_url if logged_in?
  end

end

balloon/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render new_user_goal(params[:user_id])
  end

  def index
    if params[:user_id]
      @goals = Goal.where(user_id: params[:user_id])
    else
      @goals = Goal.where(goal_type: 'public')
    end
  end

  def create
    @goal = Goal.new(goal_params, user_id: params[:user_id])
    if @goal.save
      redirect_to new_user_goal(params[:user_id])
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to new_user_goal(params[:user_id])
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :goal_type, :user_id)
  end
end

balloon/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["incorrect username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

balloon/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_out, only: [:new, :create]
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      # debugger
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

balloon/app/helpers/application_helper.rb
module ApplicationHelper
end

balloon/app/helpers/goals_helper.rb
module GoalsHelper
end

balloon/app/helpers/sessions_helper.rb
module SessionsHelper
end

balloon/app/helpers/users_helper.rb
module UsersHelper
end

balloon/app/views/goals/_form.html.erb
<h1> <%=Title%> </h1>

<form action="<%=user_goals%>" method="POST">
  <label for="title">What is your goal?
    <textarea name="goal[title]" id="title" value=""></textarea>
  </label>
  <br>

  <label for="goal_type">Goal type:
    <input type="radio" name="goal[goal_type]" value="public">Public
    <input type="radio" name="goal[goal_type]" value="private">Private
  </label>
  <br>

  <input type="submit" value="Add Goal!">
</form>

balloon/app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

balloon/app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

balloon/app/views/goals/index.html.erb
<h1>Everyone's Goals!</h1>
<ul>
    <% @goals.each do |goal| %>
      <li><%= goal.title %></li>
    <% end %>
</ul>

balloon/app/views/goals/new.html.erb
<h1>New goal:</h1>

<form action="<%=user_goals%>" method="POST">
  <label for="title">What is your goal?
    <textarea name="goal[title]" id="title" value=""></textarea>
  </label>
  <br>

  <label for="goal_type">Goal type:
    <input type="radio" name="goal[goal_type]" value="public">Public
    <input type="radio" name="goal[goal_type]" value="private">Private
  </label>
  <br>

  <input type="submit" value="Add Goal!">
</form>

balloon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Balloon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <% if logged_in? %>
    <form action="<%=session_url%>" method='POST'>
    <p>Log out here!!!</p>
      <input type="hidden" name="_method" value='DELETE'>
      <input type="submit" value='Log out'>
    </form>
  <% end %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <p><%= error %></p>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

balloon/app/views/users/_form.html.erb
<% if type == :new %>
  <% action_url = users_url %>
<% end %>


<form action="<%=action_url%>" method="post">
  <label for="username">Username
    <input id="username" type="text" name="user[username]" value="">
  </label>
  <br>

  <label for="password">Password
    <input id="password" type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign up">



</form>

balloon/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

balloon/app/views/users/new.html.erb
<h1>Sign up Balloon:</h1>

<%= render "form", user: @user, type: :new %>

balloon/app/views/users/show.html.erb
<h1>Sup <%= @user.username %></h1>